export const CHECK_NODE_STATUS_START = 'CHECK_NODE_STATUS_START';
export const CHECK_NODE_STATUS_SUCCESS = 'CHECK_NODE_STATUS_SUCCESS';
export const CHECK_NODE_STATUS_FAILURE = 'CHECK_NODE_STATUS_FAILURE';
export const GET_BLOCKS_DATA_START = 'GET_BLOCKS_DATA_START';
export const GET_BLOCKS_DATA_SUCCESS = 'GET_BLOCKS_DATA_SUCCESS';
export const GET_BLOCKS_DATA_FAILURE = 'GET_BLOCKS_DATA_FAILURE';
